# Load the data
sheet_a = [
    "Addo Elvis", "Addo Godfred", "Asante Bismark", "Kwaku Jeremiah", "Nartey Emmanuel",
    "Nartey Emmanuel", "Nettey Syliva", "Nicolas Normeye", "Novling korankye", "Patrick Paul",
    "Quanor clement aka Noble one", "Samuel Alormabor", "Tsatsu Ephraim Jewel", "Daniel Tagoe",
    "Ernest Appiah", "Samuel Aliemo", "Seshie Elinam Marcus", "True Bless", "Aaron Dickson",
    "Adjei kwesi Samuel", "Harrison Bruce", "Ike Stanley", "Irene Ayisi", "Issac Akom Afful",
    "Issac Kwame Amoako", "Issac Ampoman", "Issac Kofianu", "Issac Mensah", "James Agbeko Tay",
    "Janet Nutsua", "Blessing Tiboriwu", "Kyei Elizabeth", "Susan Conteh", "Tovor Emmanuel",
    "Belinda Foli", "Benjamin Abrokwah", "Benjamin Borteye", "Benjamin Kwame", "Gershon Azagbe",
    "Godfred Arthur", "Rosemary Amponsah", "Benard Azanila", "Benjamin Narteh", "Bernard", "Bernard",
    "Godlives Bedzra", "Bright", "Donkor", "Ferdi", "Godfrier", "Joshua", "Kumi", "Kwesi A",
    "Patrick Dzognardzi", "Prosper Dodoe", "Sakyi", "Beauty comfort Larbi", "Daniel Boateng",
    "Emmanuel Acheampong", "Eric Nyarko", "Francis Harris", "Gideon", "Keziah Esi Amponsah",
    "Mamel Eyram Lawoe", "Mary owusuwaa Danzumah", "Osabutey Esther Konadu", "Ramabella Blessing",
    "Ramabella Blessing", "Awuriwor Emmanuel", "Ayomi Bright", "Bismarck TETTEH", "Blame Rejoice",
    "David Ade", "Kaden Kodjo", "Amofa Thomas", "Godfred Owusu", "Kwesi", "Nicholas Alofa",
    "Afari Lawrence", "Aziz laryea", "Dorothy Attram", "Douglas kwame", "Emmanuel Quashie",
    "Hayford Ayitey", "Jessica Gadri", "kezia Alhassan", "Kingsley. Botchwey", "Richmond Tetteh",
    "Samuel Addo", "Samuel Quaye", "Bernard Agyeman", "Bernard Osa", "Bismarck", "Blessing Nsiah",
    "Bob Baah", "Brandon Amartey", "Bright Dzivenu", "Brobbey MyriabeL", "Delight Boateng",
    "Kofi Boadu", "Nathan Dzansi", "Obeng Theophilus", "Ababio Jacob Appiah", "Acquah Dora Fynn",
    "Christian Mensah", "Daniel", "Francis Akwertey", "Henry Aryee Mensah", "Ofosu Samuel",
    "Ofosu Samuel", "Opoku Herbert", "Steven Goha", "Addogo Bright", "Adrian Bokari",
    "Angelina Abosiminiying", "Bernard Addi", "Edward Junior", "Eric Yeboah", "Isaac Kissiedu",
    "James Adjei", "Prince Addo", "Jason Kpentey", "Joseph Sarfo", "Samuel Damage", "Afari Barrack",
    "Innocent Womernor", "Ivan Ofosu Baah", "Obed Prempeh", "Samuel Yeboah", "Shadrach Manu",
    "Solomon Blankson", "Afoakwa Wilfred", "Aguze Edem Nathaniel", "Agyekum Richard",
    "Akyea bright Sakyi Junior", "Cassiel Blankson Ewusie", "Edward Dakaroul", "Edward Dakaroul",
    "Faris Djabeng", "Francis Gbedove", "Francis Gbedove", "Geoffrey Tsorme", "Nana Amponsah",
    "Osei Patrick", "Emmanuel Annie Boafo", "Markwei Boye Amos", "Raymond Ablode",
    "Anyomi Delali Derrick", "Ayakpo Beauty", "Ayana Richmond", "David Prah", "Derick Andoh",
    "Ivy Agyeiwaa Amata", "Jacob Yemo", "Kansalorh Vera", "Kingsley Ghoos Yaw", "Prosper Amevbi",
    "Mawuli Dekpo", "Mary Quashiga", "Maxwell Quansah", "Jeremiah Nelson", "Joseph Almar",
    "Joshua Amoah", "Kelvin Doku", "Kingsford Boakye", "Kotoku Caleb", "Kwuado Godway Kej",
    "Malik Kwame Azina", "Nettey Emmanuel", "Obiri Yeboah Joseph", "Peter Vale", "Rebecca Padi",
    "Samuel Delali", "Stephen McCarthy", "Victor Beaticer", "Enoch Arthur", "Eric Amoani",
    "Erica Obenewaa Asiamah", "Ernest Oku Sakyi", "Esther Obimpeh", "Esther Tietaah",
    "Eugenia Larbi", "Jeremiah George", "Joseph Gunu", "Emmanuel Yeboah", "Emmanuel zipping Asinor",
    "Emmanuella Ali Norvor", "Emmanuel Abbey", "Emmanuel Ada", "Emmanuel Agbo", "Emmanuel Sarfo",
    "Joshua Beckon", "Joyce", "Donatus", "ElShaddai", "Emefa Dzaka", "Emma Banned", "Emmanuel Boateng",
    "Emmanuel Otoo", "Andinos", "Blankson", "Kelly", "Michael", "Tetteh", "Agnes", "Gifty Ofori",
    "Justice", "Kelly", "Kelvin", "Kenneth", "Nabayire", "Angebel Norvor", "Anku", "Anthony Jonathan",
    "Arhin Jennifer", "Arnold Hudzoo Quaye", "Emmanuel Dankwa", "Godfred Ofori", "Kingsford Sabah",
    "Lorah Partu", "Philip Akwesi Yeboah", "Samuel Monnel", "Tamakloe Abuni Mary", "Daniel Boateng",
    "Jerry Arthur", "Joseph Kesse", "Joseph kesse", "Joshua Boadu", "Kumi Isaac", "Manu Bridget",
    "Mavis Morrison", "Mensah Lydiana", "Nicholas Aidoo", "Ogundun Blessing Elizabeth", "Philip",
    "Samuel Kwapong", "Stephen Sosoo", "Vincent Kumi", "Lawrencia Dumenyo", "Kingsley Miracle Owusu",
    "Assogba Mawuena", "Benjamin Doku", "Thomas Ofali Quaye", "Tackie Naa Pamela", "David Mantial",
    "David Mantial", "Diana Dziedzom", "Emmanuel Tovor", "Evans Sebuabe", "Jacob Tetteh",
    "Pascaline Ababio", "Patience Clory Nortey", "Richmond Odam", "Samuel Antwi", "Tetteh Enoch Esseku",
    "Victor Azubike", "Yussif Michael", "Benard (A brother to Patience Clory Nortey)", "Benjamin Doku",
    "Evans Sebuabe", "Lovett Emmanuella", "Nkechi Aii", "Oluwa John Akakpo", "Pascaline Ababio",
    "Patience Clory Nortey", "Priscilla Agyei", "Samuel Antwi", "Samuel Tetteh", "Tachu Anthony",
    "Thomas Akoesso", "Wisdom Dzradosi", "Wisdom Tetteh", "Yidania Baako Samuel", "Buabeng Evans Ofori",
    "Caleb Addinortey Asamanyuah", "Charlotte Plange", "Chester Owusu Ansah", "Christian Madjetey",
    "Claudia Plange", "Clement Laryea Armi", "Collins Appiah", "Daniel Lamptey", "David Ade",
    "Ofosu Frank", "Ohene Felix", "David Okyere", "David Tettey-Wayo", "Demordzi Alfred",
    "Dike Maxwell", "Dzah Yaw Dela Cosmos", "Akpabli Celestine", "Amamu Mensah Mary",
    "Cecelia Azore", "David Hosi", "Francis Tetteh", "Godwin Cudjoe Junior", "Isaac Kwabena",
    "Joshua Lartey", "Amina Ninkabu", "Oluchi Adanma", "Princess Morrison", "Richmond Ansong",
    "Rugiatu Conteh", "Samuel Edem", "Tetteh Enoch Esseku", "Sheillo Azaveilla", "Doedor Kingsley",
    "Ebenezer Abbey", "Amawude Felix", "Issaka Sumaya", "Jeremiah Ofori", "Joy Peter",
    "Kwame Arhin", "Kwame Frimpong", "Mark Anthony", "Prince Kelvin", "Benjamin Quartey",
    "Ababio Pascaline", "Assogba Mawuena", "Benjamin Doku", "David Mantial", "Diana Dziedzom",
    "Evans Sebuabe", "Lovett Emmanuel", "Nkechi Aii", "Oluwa John Akakpo", "Pascaline Ababio",
    "Patience Clory Nortey", "Priscilla Agyei", "Samuel Antwi", "Samuel Tetteh", "Tachu Anthony",
    "Thomas Akoesso", "Wisdom Dzradosi", "Wisdom Tetteh", "Yidania Baako Samuel", "Ababio Pascaline",
    "Abraham Adjei Befa", "Acheampong Rabbi", "Danso Stephen", "Dogbey David", "Emmanuel Zormelo",
    "Louisa Apprey", "Noah Teye", "Owusu Abraham", "Priscilla Dansowaa", "Prosper Avernyo",
    "Rita Tetteh", "Sampson Mimni", "Joel Sangma", "Sarpong Asante", "Theophilus Kudozia",
    "Victoria Tagoe", "Yemetey Desmond Tetteh", "Adjei Nana", "Dennis Amoah", "Attimu Dzidzornu",
    "Edmonta Okai", "Emmanuel Tagoe", "Innocent Adekpe", "Isaac Tetteh", "Joshua Addo",
    "Bright Mensah", "Prince Sappor", "Richmond Mensah", "Ridwan Masawudu"
]

sheet_b = [
    "Aaron Dickson", "Adjei kwesi Samuel", "Harrison Bruce", "Ike Stanley", "Irene ayisi",
    "Isaac Akom Afful", "Isaac Ampoman Senior", "Isaac Kofianu", "Isaac Kwame Amoako", "Isaac Mensah",
    "James Adgeko Tay", "Janet Nutsua", "Abgenyenu Olivia", "Agnes Tether", "Blessing Tiboriwub",
    "Chinweuba Grace", "Ishmael Laryea Ala", "Kyei Elizabeth Gyamfua", "Michelle K Mensah",
    "Norquaye Dorothy", "Paciencia Makafe Sitso", "Prosper odoi", "Rosemary Ibrahim", "Sarah Ewuah",
    "Susan Conteh", "Tachu Anthony", "Thomas Akoesso", "Tovor Emmanuel", "Victor Azubike",
    "Yidania Baako Samuel", "Amponsah Rosemary Asiedu", "Arthur Godfred", "Asante Emmanuel",
    "Azagbe Gershon", "Azanila Benard", "Bati A. Joel", "Bedzra Godlives kwabla", "Belinda Foli Edem",
    "Benjamin Abrokwah", "Benjamin Borteye Borketey", "Benjamin Kwame Tei Narteh", "Bernard",
    "Adjetey Joshua", "Arthur Kusi Ferdinand", "Assinog Godfriend", "Bright Oppong", "Brigidi Blay",
    "Kweku Bright", "Margret Kuml", "Martha Sakyi", "Patrick Dorgbadzi", "Prince Donkor",
    "Prosper Dordoe", "Stephen kwesi Ayih", "Amofa Thomas", "Anyomi Bright", "Awuriwor Emmanuel",
    "Bismark Tetteh", "Blame Rejoice", "Dadzie Stephen", "David ade Oyawale", "Desmond Ohemene",
    "Godfred Owusu", "Kaden Kodjo", "Kwesi", "Nicholas Alofa", "Afari Lawrence", "Aziz Laryea",
    "Dorothy Attrams Danquah", "Douglas Kwame Gyimah Berkoh", "Emmanuel Quarshie", "Hayford Ayitey",
    "Jessica Gadri", "Kezia Alhassan Mussah", "Kingsley Botchway", "Richmond Tetteh", "Samuel Addo",
    "Samuel Quaye", "Jennifer Iheke", "Jonathan Kofi Timpong", "Joshua Afrane", "Juan Fernando Mico",
    "Keziah Buadu", "Konji Richard", "Kwaku Jeremiah", "Lovelyna Duncan", "Mary Pusiate",
    "Max Cyril Kwame Yeboah", "Mr Obed", "Nortoy Jacob", "Patricia Yevugah", "Puplampu Nyugmotey Isaac",
    "Sakuwa Bismarck", "Semi Adaneh", "Thomas Ofali Quaye", "Yussif Michael", "Ababio Jacob Appiah",
    "Abu Dominic", "Acquah Dora Fynn", "Christian Mensah", "Daniel", "Ebenezer Mawufemor Tete",
    "Edem Aguze", "Francis Akwertey", "Henry Aryee Mensah", "Ofosu Samuel", "Opoku Herbert",
    "Steven Goha", "Edward Junior", "Eric Ayikai Yeboah", "Abosiminiying Angelina", "Addo Benard",
    "Addo Prince Nana Kwame", "Addogo Bright", "Adjei James", "Adrian Duck Bokari", "Damage Samuel",
    "Isaac Kwasi Kwakye Kissiedu", "Jason Adinotey Kpentey", "Joseph Sarfo", "Afoakwa Wilfred",
    "Aguze Edem Nathaniel", "Agyekum Richard", "Akyea bright Sakyi Junior", "Cassiel Blankson Ewusie",
    "Edward Dakaroul", "Edward Dokono", "Faris Djabeng", "Francis Gbedove", "Geoffrey Tsorme",
    "Nana Amponsah", "Osei Patrick", "Gifty Tyra Edem Mills", "Gloria Sarpong", "Amponsah Benjamin",
    "Daniel D. Wesley", "David Asa", "Dream Boy", "Eric Ofori", "Fiti Abel", "Godfred Gbeku",
    "Joe Humphrey", "Osei Owusu Priscilla", "Paule Queen", "Addo Elvis", "Addo Godfred", "Asante Bismark",
    "Daniel Tagoe", "Ernest Appiah", "Kwaku Jeremiah", "Nartey Emmanuel", "Nettey Sylvia", "Nicolas Normeye",
    "Novling Korankye", "Patrick Paul", "Quanor Clement", "Samuel Aliemo", "Samuel Alormabor",
    "Tsatsu Ephraim Jewel", "Anyomi Delali Derrick", "Ayakpo Beauty", "Ayana Richmond", "David Prah",
    "Derick Andoh", "Ivy Agyeiwaa Amata", "Jacob Yemo", "Kansalorh Vera", "Kingsley Ghooss Yaw",
    "Prosper Amevbi", "Mawuli Dekpo", "Mary Quashigah", "Maxwell Quansah", "Jeremiah Nelson",
    "Joseph Almar", "Joshua Amoah", "Kelvin Doku", "Kingsford Boakye", "Kotoku Caleb", "Kwuado Godsway Kej",
    "Malik Kwame Azina", "Obiri Yeboah Joseph", "Peter Vale", "Rebecca Padi", "Samuel Delali",
    "Stephen McCarthy", "Victor Beaticer", "Enoch Arthur", "Eric Amoani", "Erica Obenewaa Asiamah",
    "Ernest Oku Sakyi", "Esther Obimpeh", "Esther Tietaah", "Eugenia Larbi", "Jeremiah George",
    "Joseph Gunu", "Emmanuel Yeboah", "Emmanuel Zipping Asinor", "Emmanuella Ali Norvor", "Enoch Arthur",
    "Eric Amoani", "Erica Obenewaa Asiamah", "Ernest Oku Sakyi", "Esther Obimpeh", "Esther Tietaah",
    "Eugenia Larbi", "Jeremiah George", "Joseph Gunu", "El-Shaadai Michael", "Eleene Donatus",
    "Emefa Dzaka", "Emma Banned", "Emmanuel Abbey", "Emmanuel Adablah Senyo", "Emmanuel Agbolosu",
    "Emmanuel Boateng", "Emmanuel Otoo", "Emmanuel Sarfo", "Joshua Beckon Tanor", "Joyce Line A Obli",
    "Andinos Adjei", "Blankson John", "Gifty Ofori", "Justice Bhalo", "Kelly Frimpong", "Kelvin Edem Bosso",
    "Kenneth Addo", "Kwateng Boateng", "Michael Dzadu", "Nabayire Webalaria Moses", "Owusu Agnes",
    "Tetteh Christopher", "Angelbel Norvor", "Anku Jonathan", "Jennifer Arhin", "Arnold Hudzoo",
    "Emmanuel Dankwa", "Godfred Ofori", "Kingsford Sabah", "Lorah Partu", "Philip Akwesi",
    "Samuel Monnel", "Tamakloe Mary", "Jerry Arthur", "Joseph Kesse", "Joshua Boadu", "Kingsley Miracle",
    "Kumi Isaac", "Lawrencia Dumenyo", "Manu Bridget", "Mavis Morrison", "Mensah Lydiana", "Micheal Agensu",
    "Nicholas Aidoo", "Blessing Ogundun", "Philip Dumevi", "Samuel Kwapong", "Stephen Sosoo",
    "Vincent Kumi", "Asare Gideon", "Comfort Larbi", "Benson Borquaye", "Daniel Boateng",
    "Emmanuel Acheampong", "Esi Keziah", "Francis Harris", "Mamel Lawoe", "Mary Danzumah",
    "Nyarko Eric", "Esther Konadu Osabutey", "Blessing Ramabella", "Bernard Prempeh", "Bernard Osa",
    "Bismark Nsiah", "Boadu Hovah", "Boateng Delight", "Bob Baah", "Brandon Amartey", "Brigth Dzivenu",
    "Brobbey Adomaa", "Nathan Dzansi", "Obeng Theophilus", "Buabeng Evans", "Caleb Asamanyuah",
    "Charlotte Plange", "Chester Ansah", "Christian Madjetey", "Claudia Plange", "Clement Armi",
    "Collins Appiah", "Daniel Lamptey", "David Ade", "Ofosu Frank", "Felix Ohene", "Nelson Acquah",
    "Frank Adjei", "Gladys Amissah", "David Acheampong", "David Umahi", "Jerry Dearly", "Ebenezer Diaz",
    "Francis Asirifi", "Lydia Osipi", "Ransford Opoku", "Isaac Adzepa", "Solomon Aboagye",
    "David Okyere", "David Tettey-Wayo", "Alfred Demordzi", "Maxwell Dike", "Yaw Dzah", "Prince Dzokoto",
    "Ebenezer Apronti", "Ebenezer Offei", "Priscilla Edinam", "Edmund Okai", "Solomon Owuh",
    "Wolfgang Worlanyo", "Jonathan Allotey", "Josephine Wellington", "Joshua Tetteh", "Elisha Kojo",
    "Chilander Kuvor", "Liandra Bill", "Mary Donkor", "Marvin Mensah", "Ayishetu Michael", "Michael Marvelous",
    "Nicholas Martin", "Johnpaul Okol", "Prince Asare", "Richard Gbni", "Samuel Mensah", "Elijah Tetteh",
    "Wendy Agyarko", "Michael Antwi", "Reginald Acquaye", "Benedict Lamptey", "Christabel Koomson",
    "Joseph Dela", "Ezekiel Bortier", "Joel Neequaye", "Jonathan Mensah", "Enoch Owuredu",
    "Saeed Majdoub", "Seth Carl", "Stephen Mensah", "Celestine Akpabli", "Mary Amamu", "Azore Cecelia",
    "David Hosi", "Tetteh Bossman", "Godwin Cudjoe", "Kwabena Isaac", "Joshua Lartey", "Amina Ninkabu",
    "Oluchi Adanma Ekeziah", "Mary Morrison", "Richmond Ansong", "Conteh Rugiatu", "Samuel Aryettey",
    "Esseku Tetteh", "Azaveilla Sheillo", "Kingsley Doedor", "Ebenezer Anero Abbey", "Felix Amawude",
    "Sumaya Issaka", "Ofori Jeremiah", "Peter Joy", "Arhin Kwame", "Kwame Frimpong", "Anthony Mark",
    "Kelvin Wonders", "Benjamin Quartey", "Pascaline Ababio", "Mawuena Assogba", "Benjamin Doku",
    "David Mantial", "Habadah Diana", "Sebastian Evans", "Lovett Emmanuel", "Nkechi Aii",
    "Oluwa John Akakpo", "Nortey Patience", "Agyei Priscilla", "Richmond Tetteh", "Samuel Antwi",
    "Tetteh Samuel", "Anthony Tachu", "Thomas Akoesso", "Wisdom Dzradosi", "Tetteh Wisdom",
    "Baako Samuel", "Pascaline Ababio", "Abraham Befa", "Rabbi Acheampong", "Stephen Danso",
    "David Dogbey", "Emmanuel Zormelo", "Apprey Louisa", "Noah Teye", "Owusu Abraham", "Priscilla Dansowaa",
    "Avernyo Prosper", "Rita Tetteh", "Mimni Sampson", "Joel Sangma", "Asante Sarpong", "Kudozia Theophilus",
    "Tagoe Victoria", "Desmond Tetteh", "Nana Adjei", "Amoah Dennis", "Attimu Dzidzornu", "Edmonta Okai",
    "Tagoe Emmanuel", "Innocent Adekpe", "Tetteh Isaac", "Addo Joshua", "Mensah Bright", "Sappor Prince",
    "Mensah Richmond", "Masawudu Ridwan"
]

def find_duplicates(sheet_a, sheet_b):
    duplicates = set(sheet_a).intersection(set(sheet_b))
    return list(duplicates)

# Find duplicates
duplicates = find_duplicates(sheet_a, sheet_b)
